apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: small-basket
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cm9vdAo="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: small-basket
data:
  DB_HOST: "small-basket-database-svc"
  DB_NAME: "vegshop"
  DB_USER: "root"
